#!/usr/bin/env node
/**
 * sync-icons.js
 *
 * 실행: pnpm sync-icons
 *
 * 1. assets/icons/*.svg 내 하드코딩 색상을 currentColor 로 교체
 *    - fill / stroke 가 none | currentColor | transparent | url(...) 이면 건너뜀
 *    - fill-opacity / stroke-opacity 는 제거 (투명도는 호출부에서 color prop으로 제어)
 * 2. assets/icons/index.ts 배럴 파일 자동 생성
 *    - import { HomeIcon } from '@/assets/icons' 형태로 사용 가능
 */

const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.resolve(__dirname, '../assets/icons');
const INDEX_PATH = path.join(ICONS_DIR, 'index.ts');

/** fill/stroke 값이 하드코딩 색상인지 판단 */
function isHardcodedColor(value) {
  const v = value.trim().toLowerCase();
  return v !== 'none' && v !== 'currentcolor' && v !== 'transparent' && !v.startsWith('url(');
}

/** SVG 문자열에서 하드코딩 색상을 currentColor 로 정규화 */
function normalizeColors(svg) {
  let out = svg;

  // fill="<color>" → fill="currentColor"
  out = out.replace(/\bfill="([^"]+)"/g, (match, color) =>
    isHardcodedColor(color) ? 'fill="currentColor"' : match,
  );

  // stroke="<color>" → stroke="currentColor"
  out = out.replace(/\bstroke="([^"]+)"/g, (match, color) =>
    isHardcodedColor(color) ? 'stroke="currentColor"' : match,
  );

  // fill-opacity / stroke-opacity 제거 (currentColor 이후 불필요)
  out = out.replace(/\s*fill-opacity="[^"]*"/g, '');
  out = out.replace(/\s*stroke-opacity="[^"]*"/g, '');

  return out;
}

/** arrow-left → ArrowLeftIcon */
function toExportName(filename) {
  return (
    path
      .basename(filename, '.svg')
      .split('-')
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join('') + 'Icon'
  );
}

function main() {
  const svgFiles = fs
    .readdirSync(ICONS_DIR)
    .filter((f) => f.endsWith('.svg'))
    .sort();

  if (svgFiles.length === 0) {
    console.log('assets/icons/ 에 SVG 파일이 없습니다.');
    return;
  }

  let colorFixed = 0;

  console.log('── 색상 정규화 ──────────────────────────────');
  for (const file of svgFiles) {
    const filePath = path.join(ICONS_DIR, file);
    const original = fs.readFileSync(filePath, 'utf8');
    const updated = normalizeColors(original);

    if (original !== updated) {
      fs.writeFileSync(filePath, updated, 'utf8');
      console.log(`  ✓ ${file}`);
      colorFixed++;
    } else {
      console.log(`  · ${file} (변경 없음)`);
    }
  }

  console.log('\n── 배럴 index.ts 생성 ───────────────────────');
  const lines = [
    '// Auto-generated by scripts/sync-icons.js — do not edit manually',
    ...svgFiles.map((file) => {
      const stem = path.basename(file, '.svg');
      const name = toExportName(file);
      return `export { default as ${name} } from './${stem}.svg';`;
    }),
    '',
  ];

  fs.writeFileSync(INDEX_PATH, lines.join('\n'), 'utf8');
  console.log(`  ✓ index.ts (${svgFiles.length}개 아이콘 등록)`);

  console.log(`\n완료: SVG ${colorFixed}개 색상 교체, index.ts 재생성`);
  console.log('\n사용법:');
  console.log("  import { HomeIcon, MessageTextIcon } from '@/assets/icons';");
}

main();
